<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pizzeria" nsURI="http://www.example.org/pizzeria" nsPrefix="pizzeria">
  <eClassifiers xsi:type="ecore:EClass" name="Pizza">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredient" upperBound="-1"
        eType="#//Ingredient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ingredient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tomate" eSuperTypes="#//Ingredient"/>
  <eClassifiers xsi:type="ecore:EClass" name="Jambon" eSuperTypes="#//Ingredient"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fromage" eSuperTypes="#//Ingredient"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pizzeria">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizza" upperBound="-1"
        eType="#//Pizza" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
